#!/usr/bin/env node
/**
 * Generates the `@ghicons/react` package from the canonical icon collection.
 *
 *   packages/react/src/icons/<category>/<Name>.tsx
 *   packages/react/src/index.ts
 *
 * Both are rebuilt from scratch on every run. The previous generator appended
 * to the barrel and skipped existing components, which left exports pointing at
 * icons that had been renamed or deleted and broke the build until someone
 * deleted the file by hand.
 *
 * Run from the repository root.
 */

import fs from 'node:fs';
import path from 'node:path';
import { loadIcons } from '../canonical.mjs';

/**
 * SVG carries hyphenated presentation attributes (`fill-rule`, `stroke-width`);
 * JSX wants them camelCased. Passing the hyphenated form through makes React
 * log "Invalid DOM property" for every icon that uses one — 17 of them do.
 *
 * `data-*` and `aria-*` stay hyphenated, which is what React expects.
 */
function toJsxAttributes(body) {
    return body.replace(
        /(\s)([a-z]+(?:-[a-z]+)+)=/g,
        (match, space, name) =>
            name.startsWith('data-') || name.startsWith('aria-')
                ? match
                : `${space}${name.replace(/-([a-z])/g, (_, c) => c.toUpperCase())}=`
    );
}

const PKG = 'packages/react';
const ICONS_DIR = `${PKG}/src/icons`;
const BARREL = `${PKG}/src/index.ts`;

function component(icon, propsImport) {
    return `import * as React from "react";
import { type IconProps, trueSize } from '${propsImport}';

/**
 * ${icon.name} — ${icon.category} icon.
 *
 * Accepts \`IconProps\`: \`size\` (number or any CSS unit), \`color\`, \`viewBox\`,
 * and every standard SVG attribute. Defaults to 24px and \`currentColor\`, so it
 * inherits the surrounding text colour unless told otherwise.
 *
 * Generated from ${icon.file} — edit that, not this file.
 */
const ${icon.name}: React.FC<IconProps> = ({ size = 24, color = 'currentColor', viewBox = "${icon.viewBox}", ...props }) => (
  <svg xmlns="http://www.w3.org/2000/svg" width={trueSize(size)} height={trueSize(size)} fill={color} viewBox={viewBox} {...props}>${toJsxAttributes(icon.body)}</svg>
);

export default ${icon.name};
`;
}

const icons = loadIcons();

fs.rmSync(ICONS_DIR, { recursive: true, force: true });
fs.rmSync(BARREL, { force: true });

for (const icon of icons) {
    const dir = path.join(ICONS_DIR, icon.category);
    fs.mkdirSync(dir, { recursive: true });

    const propsImport = path
        .relative(dir, `${PKG}/src/props`)
        .split(path.sep)
        .join('/');

    fs.writeFileSync(path.join(dir, `${icon.name}.tsx`), component(icon, propsImport));
}

const barrel = `// Generated by tools/generators/react.mjs — do not edit.
// Source of truth: svg/ in the ghicons repository.

// Types only. The public runtime surface is exactly the icons — trueSize is an
// internal sizing helper, and exporting it made every consumer enumerating the
// package see a 107th "icon".
export type { IconProps, IconComponent, IconMap } from './props';

${icons.map((i) => `export { default as ${i.name} } from './icons/${i.category}/${i.name}';`).join('\n')}
`;

fs.writeFileSync(BARREL, barrel);

console.log(`@ghicons/react: ${icons.length} components and a rebuilt barrel written to ${PKG}/src/`);
