#!/usr/bin/env node
/**
 * Builds the `ghicons` core package: the framework-agnostic distribution.
 *
 *   packages/core/svg/<category>/<Name>.svg   optimised canonical artwork
 *   packages/core/registry.json               the machine-readable index
 *   packages/core/index.js / .cjs / .d.ts     convenience entry points
 *
 * Everything it writes is generated and git-ignored. Run it from the
 * repository root.
 */

import fs from 'node:fs';
import path from 'node:path';
import { loadIcons, fromRoot } from './canonical.mjs';

const OUT = fromRoot('packages/core');
const pkg = JSON.parse(fs.readFileSync(`${OUT}/package.json`, 'utf8'));

// Rebuilt from scratch every run: an incremental update would leave artifacts
// behind for icons that have since been renamed or deleted.
for (const stale of ['svg', 'registry.json', 'index.js', 'index.cjs', 'index.d.ts']) {
    fs.rmSync(path.join(OUT, stale), { recursive: true, force: true });
}

const icons = loadIcons();

// ── SVG assets ────────────────────────────────────────────────────────────────

for (const icon of icons) {
    const dest = path.join(OUT, 'svg', icon.category, `${icon.name}.svg`);
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.writeFileSync(dest, icon.svg);
}

// ── Registry ──────────────────────────────────────────────────────────────────

// Metadata only. The artwork stays in the SVG files so the index remains small
// enough to ship to a browser and query cheaply.
//
// Derived fields are written first and the authored ones spread over them, so
// the shape is predictable; a sidecar cannot overwrite a derived field because
// validation rejects one that names it.
const entries = icons.map(({ name, slug, category, viewBox, file, metadata }) => ({
    name,
    slug,
    category,
    viewBox,
    file,
    ...metadata,
}));

const registry = {
    version: pkg.version,
    // Was `generated`, which held the icon count — a field named for a
    // timestamp it never carried. A real timestamp would break reproducible
    // regeneration, so the count stays and the name now matches it.
    count: entries.length,
    categories: [...new Set(entries.map((e) => e.category))].sort(),
    icons: entries,
};

fs.writeFileSync(`${OUT}/registry.json`, `${JSON.stringify(registry, null, 2)}\n`);

// ── Entry points ──────────────────────────────────────────────────────────────

// The data is inlined rather than read from registry.json at runtime, so the
// entry points work in a browser bundle as well as in Node. registry.json
// remains the canonical file for consumers that are not running JavaScript.
const data = JSON.stringify(registry, null, 2);

const banner =
    '// Generated by tools/build-core.mjs — do not edit.\n' +
    '// Source of truth: svg/ in the ghicons repository.\n';

fs.writeFileSync(
    `${OUT}/index.js`,
    `${banner}
export const registry = ${data};

export const icons = registry.icons;
export const categories = registry.categories;

export function getIcon(slug) {
  return registry.icons.find((icon) => icon.slug === slug);
}

export function iconsByCategory(category) {
  return registry.icons.filter((icon) => icon.category === category);
}
`
);

fs.writeFileSync(
    `${OUT}/index.cjs`,
    `${banner}
const registry = ${data};

module.exports = {
  registry,
  icons: registry.icons,
  categories: registry.categories,
  getIcon: (slug) => registry.icons.find((icon) => icon.slug === slug),
  iconsByCategory: (category) => registry.icons.filter((icon) => icon.category === category),
};
`
);

fs.writeFileSync(
    `${OUT}/index.d.ts`,
    `${banner}
/** A single icon in the GHIcons collection. */
export interface Icon {
  /** PascalCase name, and the identifier used by framework integrations. */
  name: string;
  /** Kebab-case identifier, stable across every distribution channel. */
  slug: string;
  /** The icon's category, taken from its directory in the collection. */
  category: string;
  /** Always "0 0 24 24" — see docs/ICON-SPEC.md. */
  viewBox: string;
  /** Path to the SVG within this package, e.g. "svg/adinkra/GyeNyame.svg". */
  file: string;
  /** Documented meaning of the symbol, where it has been researched. */
  meaning?: string;
  /** Longer context: origin, variations, or a contested reading. */
  note?: string;
  /** Search keywords. */
  keywords?: string[];
  /** Alternate and vernacular names. */
  aliases?: string[];
  /** Sources the meaning was taken from. Present wherever a meaning is. */
  references?: string[];
}

export interface Registry {
  version: string;
  /** Number of icons in the collection. */
  count: number;
  categories: string[];
  icons: Icon[];
}

export declare const registry: Registry;
export declare const icons: Icon[];
export declare const categories: string[];
export declare function getIcon(slug: string): Icon | undefined;
export declare function iconsByCategory(category: string): Icon[];
`
);

const bytes = icons.reduce((n, i) => n + i.svg.length, 0);
const documented = entries.filter((e) => e.meaning).length;
console.log(
    `ghicons core: ${icons.length} icons in ${registry.categories.length} categories ` +
    `(${(bytes / 1024).toFixed(1)} KB of SVG), registry.json + entry points written to ${OUT}/`
);
// Printed every build because it is the project's most useful open number, and
// the one nobody goes looking for.
console.log(
    `  ${documented}/${icons.length} have a documented meaning` +
    `${documented === icons.length ? '' : ' — see docs/wiki/Cultural-Guidelines.md'}`
);
